CREATE TABLE IF NOT EXISTS auto_command_exec
(
    `id`         INT AUTO_INCREMENT PRIMARY KEY,
    `type`       VARCHAR(20) NOT NULL COMMENT '指令类型',
    `created_at` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `status`     VARCHAR(20) NOT NULL,
    `updated_at` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)